name: hello-world
on: push
jobs:
  my-job:
    continue-on-error: true
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set-env
        run: |
          echo "GITHUB_COMMIT_MESSAGE=$(git log -1 --format='%s')" >> $GITHUB_ENV
      - name: validate-commit-message-tag
        id: validate-commit-message-tag
        run: |
          echo "Hello World!"
          echo $GITHUB_COMMIT_MESSAGE
          if [[ $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_MAJOR]"* || 
                  $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_MINOR]"* ||
                  $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_BUG_FIX]"* ||
                  $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_OTHER]"* ]]; then
            echo "GMVIEWS tag required for automated release notes does exists"
          else
            echo "GMVIEWS tag required for automated release notes does NOT exists"
            exit 1
          fi
      - name: post-failure-comment-on-pr
        if: failure() && steps.validate-commit-message-tag.outcome == 'failure'
        env:
          URL: "https://api.github.com/repos/dhruvjariwala/SampleRSSFeedReader/issues/comments"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo "$URL"
          echo "$GITHUB_TOKEN"
          echo "$PR_NUMBER"
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "blah blah" }'
