name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set-env
        run: echo "GITHUB_COMMIT_MESSAGE=$(git log -1 --format='%s')" >> $GITHUB_ENV
      - name: my-step
        run: |
          echo "Hello World!"
          echo $GITHUB_COMMIT_MESSAGE
          if [[ $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_MINOR]"* || $GITHUB_COMMIT_MESSAGE == *"[GMVIEWS_BUG_FIX]"* ]]; then
            echo "GMVIEWS_MINOR exists"
          else
            echo "No TAG exists"
            exit 1
          fi
