name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: my-step
        run: |
          echo "Hello World!"
          git log -1 --format='%s'
          if [[ ${{ git log -1 --format='%s' }} == *"[GMVIEWS_MINOR]"* ]]; then
            echo "GMVIEWS_MINOR exists"
          else
            echo "No TAG exists"
          fi
